/*
 * generated by Xtext 2.13.0
 */
package org.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.HashMap;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.ide.contentassist.antlr.internal.InternalSchemeParser;
import org.xtext.services.SchemeGrammarAccess;

public class SchemeParser extends AbstractContentAssistParser {

	@Inject
	private SchemeGrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalSchemeParser createParser() {
		InternalSchemeParser result = new InternalSchemeParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getFunctionIdAccess().getAlternatives(), "rule__FunctionId__Alternatives");
					put(grammarAccess.getFunctionParamAccess().getAlternatives(), "rule__FunctionParam__Alternatives");
					put(grammarAccess.getFunctionAccess().getAlternatives_1(), "rule__Function__Alternatives_1");
					put(grammarAccess.getBooleanOperationAccess().getAlternatives_0(), "rule__BooleanOperation__Alternatives_0");
					put(grammarAccess.getBooleanOperationAccess().getAlternatives_1(), "rule__BooleanOperation__Alternatives_1");
					put(grammarAccess.getBooleanAccess().getAlternatives(), "rule__Boolean__Alternatives");
					put(grammarAccess.getFunctionAccess().getGroup(), "rule__Function__Group__0");
					put(grammarAccess.getFunctionAccess().getGroup_1_0(), "rule__Function__Group_1_0__0");
					put(grammarAccess.getBooleanOperationAccess().getGroup(), "rule__BooleanOperation__Group__0");
					put(grammarAccess.getBooleanOperationAccess().getGroup_1_0(), "rule__BooleanOperation__Group_1_0__0");
					put(grammarAccess.getBooleanOperationAccess().getGroup_1_1(), "rule__BooleanOperation__Group_1_1__0");
					put(grammarAccess.getModelAccess().getFunctionsAssignment(), "rule__Model__FunctionsAssignment");
					put(grammarAccess.getFunctionAccess().getIdAssignment_1_0_0(), "rule__Function__IdAssignment_1_0_0");
					put(grammarAccess.getFunctionAccess().getParamsAssignment_1_0_1(), "rule__Function__ParamsAssignment_1_0_1");
					put(grammarAccess.getFunctionAccess().getBlAssignment_1_1(), "rule__Function__BlAssignment_1_1");
				}
			};
		}
		return nameMappings.get(element);
	}
			
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public SchemeGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SchemeGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
