grammar org.xtext.Scheme with org.eclipse.xtext.common.Terminals

generate scheme "http://www.xtext.org/Scheme"

Model:
	functions+=Function*;
	
terminal SCHEME_ID: ('a'..'z'|'A'..'Z') ('a'..'z'|'A'..'Z'|'-')*;

Boolean:
	"#t" | "#f" | "0" | "1"
;

Math:
	"+" | "-" | "*" | "/" | "="
;

Variable:
	"not"? (INT | ID | Boolean | Math | SCHEME_ID | Function)
;

Function:
	'(' SCHEME_ID Variable* ')'
;
