/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ui.labeling;

/**
 * Provides labels for EObjects.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class SchemeLabelProvider /* implements DefaultEObjectLabelProvider  */{
  /* @Inject
   */public SchemeLabelProvider(final /* AdapterFactoryLabelProvider */Object delegate) {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method super(AdapterFactoryLabelProvider) is undefined");
  }
}
