/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ui.labeling;

/**
 * Provides labels for IEObjectDescriptions and IResourceDescriptions.
 * 
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#label-provider
 */
@SuppressWarnings("all")
public class SchemeDescriptionLabelProvider /* implements DefaultDescriptionLabelProvider  */{
}
