/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ui;

import org.xtext.ui.AbstractSchemeUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
/* @FinalFieldsConstructor */@SuppressWarnings("all")
public class SchemeUiModule extends AbstractSchemeUiModule {
}
