/*
 * generated by Xtext 2.13.0
 */
package org.xtext.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder.AbstractGrammarElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class SchemeGrammarAccess extends AbstractGrammarElementFinder {
	
	public class ModelElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Scheme.Model");
		private final Assignment cFunctionsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cFunctionsFunctionParserRuleCall_0 = (RuleCall)cFunctionsAssignment.eContents().get(0);
		
		//Model:
		//	functions+=Function*;
		@Override public ParserRule getRule() { return rule; }
		
		//functions+=Function*
		public Assignment getFunctionsAssignment() { return cFunctionsAssignment; }
		
		//Function
		public RuleCall getFunctionsFunctionParserRuleCall_0() { return cFunctionsFunctionParserRuleCall_0; }
	}
	public class FunctionIdElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Scheme.FunctionId");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cOPERATORTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cSCHEME_IDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//FunctionId:
		//	OPERATOR | SCHEME_ID;
		@Override public ParserRule getRule() { return rule; }
		
		//OPERATOR | SCHEME_ID
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//OPERATOR
		public RuleCall getOPERATORTerminalRuleCall_0() { return cOPERATORTerminalRuleCall_0; }
		
		//SCHEME_ID
		public RuleCall getSCHEME_IDTerminalRuleCall_1() { return cSCHEME_IDTerminalRuleCall_1; }
	}
	public class FunctionParamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Scheme.FunctionParam");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBooleanParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//FunctionParam:
		//	INT | ID | Boolean;
		@Override public ParserRule getRule() { return rule; }
		
		//INT | ID | Boolean
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//INT
		public RuleCall getINTTerminalRuleCall_0() { return cINTTerminalRuleCall_0; }
		
		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
		
		//Boolean
		public RuleCall getBooleanParserRuleCall_2() { return cBooleanParserRuleCall_2; }
	}
	public class FunctionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Scheme.Function");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Assignment cIdAssignment_1_0_0 = (Assignment)cGroup_1_0.eContents().get(0);
		private final RuleCall cIdFunctionIdParserRuleCall_1_0_0_0 = (RuleCall)cIdAssignment_1_0_0.eContents().get(0);
		private final Assignment cParamsAssignment_1_0_1 = (Assignment)cGroup_1_0.eContents().get(1);
		private final RuleCall cParamsFunctionParamParserRuleCall_1_0_1_0 = (RuleCall)cParamsAssignment_1_0_1.eContents().get(0);
		private final Assignment cBlAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final RuleCall cBlBooleanOperationParserRuleCall_1_1_0 = (RuleCall)cBlAssignment_1_1.eContents().get(0);
		private final Keyword cRightParenthesisKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//Function:
		//	'(' (id=FunctionId params+=FunctionParam* | bl=BooleanOperation) ')';
		@Override public ParserRule getRule() { return rule; }
		
		//'(' (id=FunctionId params+=FunctionParam* | bl=BooleanOperation) ')'
		public Group getGroup() { return cGroup; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_0() { return cLeftParenthesisKeyword_0; }
		
		//id=FunctionId params+=FunctionParam* | bl=BooleanOperation
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//id=FunctionId params+=FunctionParam*
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//id=FunctionId
		public Assignment getIdAssignment_1_0_0() { return cIdAssignment_1_0_0; }
		
		//FunctionId
		public RuleCall getIdFunctionIdParserRuleCall_1_0_0_0() { return cIdFunctionIdParserRuleCall_1_0_0_0; }
		
		//params+=FunctionParam*
		public Assignment getParamsAssignment_1_0_1() { return cParamsAssignment_1_0_1; }
		
		//FunctionParam
		public RuleCall getParamsFunctionParamParserRuleCall_1_0_1_0() { return cParamsFunctionParamParserRuleCall_1_0_1_0; }
		
		//bl=BooleanOperation
		public Assignment getBlAssignment_1_1() { return cBlAssignment_1_1; }
		
		//BooleanOperation
		public RuleCall getBlBooleanOperationParserRuleCall_1_1_0() { return cBlBooleanOperationParserRuleCall_1_1_0; }
		
		//')'
		public Keyword getRightParenthesisKeyword_2() { return cRightParenthesisKeyword_2; }
	}
	public class BooleanOperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Scheme.BooleanOperation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Alternatives cAlternatives_0 = (Alternatives)cGroup.eContents().get(0);
		private final Keyword cOrKeyword_0_0 = (Keyword)cAlternatives_0.eContents().get(0);
		private final Keyword cAndKeyword_0_1 = (Keyword)cAlternatives_0.eContents().get(1);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Group cGroup_1_0 = (Group)cAlternatives_1.eContents().get(0);
		private final Keyword cNotKeyword_1_0_0 = (Keyword)cGroup_1_0.eContents().get(0);
		private final RuleCall cBooleanParserRuleCall_1_0_1 = (RuleCall)cGroup_1_0.eContents().get(1);
		private final Group cGroup_1_1 = (Group)cAlternatives_1.eContents().get(1);
		private final Keyword cLeftParenthesisKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final RuleCall cBooleanOperationParserRuleCall_1_1_1 = (RuleCall)cGroup_1_1.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_1_1_2 = (Keyword)cGroup_1_1.eContents().get(2);
		
		//BooleanOperation:
		//	("or" | "and")? (('not'? Boolean)* | '(' BooleanOperation ')');
		@Override public ParserRule getRule() { return rule; }
		
		//("or" | "and")? (('not'? Boolean)* | '(' BooleanOperation ')')
		public Group getGroup() { return cGroup; }
		
		//("or" | "and")?
		public Alternatives getAlternatives_0() { return cAlternatives_0; }
		
		//"or"
		public Keyword getOrKeyword_0_0() { return cOrKeyword_0_0; }
		
		//"and"
		public Keyword getAndKeyword_0_1() { return cAndKeyword_0_1; }
		
		//('not'? Boolean)* | '(' BooleanOperation ')'
		public Alternatives getAlternatives_1() { return cAlternatives_1; }
		
		//('not'? Boolean)*
		public Group getGroup_1_0() { return cGroup_1_0; }
		
		//'not'?
		public Keyword getNotKeyword_1_0_0() { return cNotKeyword_1_0_0; }
		
		//Boolean
		public RuleCall getBooleanParserRuleCall_1_0_1() { return cBooleanParserRuleCall_1_0_1; }
		
		//'(' BooleanOperation ')'
		public Group getGroup_1_1() { return cGroup_1_1; }
		
		//'('
		public Keyword getLeftParenthesisKeyword_1_1_0() { return cLeftParenthesisKeyword_1_1_0; }
		
		//BooleanOperation
		public RuleCall getBooleanOperationParserRuleCall_1_1_1() { return cBooleanOperationParserRuleCall_1_1_1; }
		
		//')'
		public Keyword getRightParenthesisKeyword_1_1_2() { return cRightParenthesisKeyword_1_1_2; }
	}
	public class BooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Scheme.Boolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//Boolean:
		//	"#t" | "#f";
		@Override public ParserRule getRule() { return rule; }
		
		//"#t" | "#f"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//"#t"
		public Keyword getTKeyword_0() { return cTKeyword_0; }
		
		//"#f"
		public Keyword getFKeyword_1() { return cFKeyword_1; }
	}
	
	
	private final ModelElements pModel;
	private final TerminalRule tSCHEME_ID;
	private final TerminalRule tOPERATOR;
	private final FunctionIdElements pFunctionId;
	private final FunctionParamElements pFunctionParam;
	private final FunctionElements pFunction;
	private final BooleanOperationElements pBooleanOperation;
	private final BooleanElements pBoolean;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SchemeGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pModel = new ModelElements();
		this.tSCHEME_ID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Scheme.SCHEME_ID");
		this.tOPERATOR = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.Scheme.OPERATOR");
		this.pFunctionId = new FunctionIdElements();
		this.pFunctionParam = new FunctionParamElements();
		this.pFunction = new FunctionElements();
		this.pBooleanOperation = new BooleanOperationElements();
		this.pBoolean = new BooleanElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.Scheme".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Model:
	//	functions+=Function*;
	public ModelElements getModelAccess() {
		return pModel;
	}
	
	public ParserRule getModelRule() {
		return getModelAccess().getRule();
	}
	
	//terminal SCHEME_ID:
	//	('a'..'z' | 'A'..'Z') ('a'..'z' | 'A'..'Z' | '-')*;
	public TerminalRule getSCHEME_IDRule() {
		return tSCHEME_ID;
	}
	
	//terminal OPERATOR:
	//	'+' | '-' | '*' | '/';
	public TerminalRule getOPERATORRule() {
		return tOPERATOR;
	}
	
	//FunctionId:
	//	OPERATOR | SCHEME_ID;
	public FunctionIdElements getFunctionIdAccess() {
		return pFunctionId;
	}
	
	public ParserRule getFunctionIdRule() {
		return getFunctionIdAccess().getRule();
	}
	
	//FunctionParam:
	//	INT | ID | Boolean;
	public FunctionParamElements getFunctionParamAccess() {
		return pFunctionParam;
	}
	
	public ParserRule getFunctionParamRule() {
		return getFunctionParamAccess().getRule();
	}
	
	//Function:
	//	'(' (id=FunctionId params+=FunctionParam* | bl=BooleanOperation) ')';
	public FunctionElements getFunctionAccess() {
		return pFunction;
	}
	
	public ParserRule getFunctionRule() {
		return getFunctionAccess().getRule();
	}
	
	//BooleanOperation:
	//	("or" | "and")? (('not'? Boolean)* | '(' BooleanOperation ')');
	public BooleanOperationElements getBooleanOperationAccess() {
		return pBooleanOperation;
	}
	
	public ParserRule getBooleanOperationRule() {
		return getBooleanOperationAccess().getRule();
	}
	
	//Boolean:
	//	"#t" | "#f";
	public BooleanElements getBooleanAccess() {
		return pBoolean;
	}
	
	public ParserRule getBooleanRule() {
		return getBooleanAccess().getRule();
	}
	
	//terminal ID:
	//	'^'? ('a'..'z' | 'A'..'Z' | '_') ('a'..'z' | 'A'..'Z' | '_' | '0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt:
	//	'0'..'9'+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//	'"' ('\\' . | !('\\' | '"'))* '"' |
	//	"'" ('\\' . | !('\\' | "'"))* "'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT:
	//	'/*'->'*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT:
	//	'//' !('\n' | '\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS:
	//	' ' | '\t' | '\r' | '\n'+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
