/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ide;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SchemeIdeModule /* implements AbstractSchemeIdeModule  */{
}
