/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ide;

import com.google.inject.Injector;
import org.xtext.SchemeStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SchemeIdeSetup extends SchemeStandaloneSetup {
  @Override
  public Injector createInjector() {
    throw new Error("Unresolved compilation problems:"
      + "\nType mismatch: cannot convert from SchemeRuntimeModule to Module"
      + "\nType mismatch: cannot convert from SchemeIdeModule to Module");
  }
}
