/**
 * generated by Xtext 2.12.0
 */
package org.xtext;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SchemeStandaloneSetup /* implements SchemeStandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type SchemeStandaloneSetup");
  }
}
