/**
 * generated by Xtext 2.12.0
 */
package org.xtext.ui.outline;

/**
 * Customization of the default outline structure.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#outline
 */
@SuppressWarnings("all")
public class SchemeOutlineTreeProvider /* implements DefaultOutlineTreeProvider  */{
}
